openapi: 3.0.0
info:
  title: Test
  version: 1.0.0
  description: quarkus kiota integration test
paths:
  /quarkus-kiota:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeting"
          description: Test
      description: Returns an hello world
components:
  schemas:
    Greeting:
      type: object
      properties:
        value:
          type: string
